import oneuplogo2 from '../images/oneup2.png'

export default function Head() {
  return (
    <>
      <title>OneUp Cartel</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by kicky" />
      <link rel="icon" href={oneuplogo2.src} />
    </>
  )
}
